### ISSUE TITLE
FetchXML filter setting field truncation after 100 characters

### ISSUE THREAD

**Issue by malkhawaja** [NielsMinnee/NNDropdown#1]
Hi,
First of all this is an awesome PCF control, and thank you for it.
I discovered that there might be a bug on the "TargetEntityFilter" in which we enter the FetchXML filter, but the field truncates everything after 100 characters, which breaks the filter and the control.

appreciate looking into it.

Thanks

**Comment by NielsMinnee** [comment]
Ah! thanks @malkhawaja I should have made this more clear in the readme.

The Property Element Multiple can contain up to 1,048,576 text characters. However the Model Driven App GUI allows a max length of 100 characters. This can be bypassed by a simple 'hack' via developer tools (F12). See Below

[Overview of the PCF Property Elements](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/manifest-schema-reference/property)

![Manipulate_Max_Length](https://user-images.githubusercontent.com/12555704/104915385-dba33100-5990-11eb-858a-e9af727bc809.PNG)

**Comment by malkhawaja** [comment]
Thanks @NielsMinnee for your prompt response... yes I was able to implement it as per the above instructions. but the records do not save! am I missing anything else?
