### ISSUE TITLE
Control is not displayed in lookup field

### ISSUE THREAD

**Issue by AlmudenadelaLlave** [NielsMinnee/NNDropdown#14]
Despite import the solution, creating the NN relationship and the search field, the NN Dropdown control does not appear in the search field.

![image](https://user-images.githubusercontent.com/67367065/213242587-30e730b6-0979-49ae-9f62-b7794ca0f75b.png)

What could be the problem?

**Comment by cbovikings** [comment]
You need to bind it to a Single Line of Text field. I had the same assumption to use a Lookup field.

**Comment by NielsMinnee** [comment]
Indeed, closing this issue. Binding the PCF control is only possible on a Single Line of Text.
The Single Line of Text is just a "phantom" field and not being use.
