### ISSUE TITLE
The control does not save

### ISSUE THREAD

**Issue by malkhawaja** [NielsMinnee/NNDropdown#2]
Hi,
I was able to implement the custom control and with the filter too, and the records show up from the target entity very nicely...but it does not save any data to the relationship!
am I missing anything here?

**Comment by NielsMinnee** [comment]
Can share a screenshot of the browser console? Any error messages over there? Have you enabled logging (See Params)

**Comment by malkhawaja** [comment]
there does not seem to appear any errors in the console! and the logging is set to True.

![Screenshot (40)](https://user-images.githubusercontent.com/43861985/105208930-ece76b80-5b51-11eb-88d6-370aeacc6cb1.png)

**Comment by malkhawaja** [comment]
after digging in the console I found this error:
"Cannot send the request because of the serializatoin failure: No metadata is available for the relationship with the name drm1_conference_drm1_specialty_drm1_speci and target entity drm1_conference"

**Comment by malkhawaja** [comment]
So i figured it out... it appeared that i have been using small caps in the relationship name while it should remain as : drm1_Conference_drm1_Specialty_drm1_Speci

everything is working perfectly now... thanks.

**Comment by NielsMinnee** [comment]
Nice! So cool. Sorry, having dinner right now, was planning to respond to check the N:N naming via customizations/relationships

Message can be short, sent from my mobile
________________________________

**Comment by malkhawaja** [comment]
Thanks again for this awesome control... and enjoy your dinner!!
