### ISSUE TITLE
Dynamic values to the filter fetchxml ?

### ISSUE THREAD

**Issue by mdashrafcrm** [NielsMinnee/NNDropdown#3]
is it possible to pass the values to the filter fetchxml, i have filter on the fetchxml to show values for country, can this country value be dynamically changed based on parent entity field value (country)

**Comment by NielsMinnee** [comment]
Hi, that's not possible at the moment with the current state of this PCF Control. However there is a way of getting this working.

You could create a multi line text field on the form, onChange of the Country field, you can set the fetchXml in that multiline text field. Change the PCF Control Filter to the form field. (Basic bounding)
